//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KucsaManagementSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMember()
        {
            this.TblProjects = new HashSet<TblProject>();
        }
    
        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public string MemberRegistration { get; set; }
        public byte[] MemberThumbnail { get; set; }
        public byte[] MemberBigPicture { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public int RoleId { get; set; }
        public byte[] TimeJoined { get; set; }
        public string Password { get; set; }
    
        public virtual TblCourse TblCourse { get; set; }
        public virtual TblModule TblModule { get; set; }
        public virtual TblRole TblRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProject> TblProjects { get; set; }
    }
}
