//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KucsaManagementSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblModule()
        {
            this.TblMembers = new HashSet<TblMember>();
        }
    
        public int ModuleId { get; set; }
        public string Title { get; set; }
        public string ModuleLeader { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMember> TblMembers { get; set; }
    }
}
