//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KucsaManagementSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProject
    {
        public int ProjectId { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectDesc { get; set; }
        public string ProjectLink { get; set; }
        public byte[] ProjectThumbnail { get; set; }
        public byte[] ProjectBigPic { get; set; }
        public int LanguageId { get; set; }
        public int MemberId { get; set; }
    
        public virtual TblLanguage TblLanguage { get; set; }
        public virtual TblMember TblMember { get; set; }
    }
}
